version: '3'
services:
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    ports:
      - "3000:3000"
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
    depends_on:
      - ollama

  api:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - ollama
