services:
  app:
    build: .
    container_name: nabil_app
    ports:
      - "8000:8000"  # Expose port 8000 for FastAPI
    volumes:
      - ./data:/app/data
      - ./static:/app/static
      - ./templates:/app/templates
      - ./myapp:/app/myapp
    depends_on:
      - ollama
    restart: always
    environment:
      - PYTHONPATH=/app
      - OLLAMA_MODELS=qwen2.5:72b
    command: ["uvicorn", "myapp.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    networks:
      - app-network

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"  # Ollama API port
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_MODELS=qwen2.5:72b
    restart: always
    networks:
      - app-network

  open-web-ui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-web-ui
    ports:
      - "4000:3000"  # Expose Open Web UI on port 4000 (host) -> 3000 (container)
    environment:
      - FASTAPI_URL=http://nabil_app:8000  # Corrected to point to FastAPI on port 8000
    depends_on:
      - app
    networks:
      - app-network

volumes:
  ollama_data:

networks:
  app-network: